/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './date-fns.module';
class DateFnsModuleInjector extends import0.ɵNgModuleInjector<import1.DateFnsModule> {
  _DateFnsModule_0:import1.DateFnsModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.DateFnsModule {
    this._DateFnsModule_0 = new import1.DateFnsModule();
    return this._DateFnsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.DateFnsModule)) { return this._DateFnsModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DateFnsModuleNgFactory:import0.NgModuleFactory<import1.DateFnsModule> = new import0.NgModuleFactory<any>(DateFnsModuleInjector,import1.DateFnsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvYW4vRGV2ZWxvcG1lbnQvcHJvamVjdHMvbmd4LWRhdGUtZm5zL3NyYy9kYXRlLWZucy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9hbi9EZXZlbG9wbWVudC9wcm9qZWN0cy9uZ3gtZGF0ZS1mbnMvc3JjL2RhdGUtZm5zLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
